services:
  - type: web
    name: eformx-backend
    runtime: docker
    region: singapore
    plan: free


    envVars:
      - key: APP_KEY
        generateValue: true
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false

      - key: MAIL_MAILER
        value: brevo
      - key: BREVO_API_KEY
        sync: false
      - key: MAIL_FROM_ADDRESS
        value: aljonrisasalonzo@gmail.com
      - key: MAIL_FROM_NAME
        value: "EFormX"

      - key: DB_URL
        fromDatabase:
          name: eformx-db
          property: connectionString
      - key: DB_CONNECTION
        value: pgsql
      - key: RUN_SEEDS
        value: true
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend

databases:
  - name: eformx-db
    databaseName: eformx
    user: eformx_user
    plan: free
    region: singapore
