services:
  - type: web
    name: eformx-backend
    runtime: docker
    region: singapore
    plan: free


    envVars:
      - key: APP_KEY
        generateValue: true
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false

      - key: DB_URL
        fromDatabase:
          name: eformx-db
          property: connectionString
      - key: DB_CONNECTION
        value: pgsql
    buildCommand: docker build -t eformx-backend .

    dockerContext: ./backend

databases:
  - name: eformx-db
    databaseName: eformx
    user: eformx_user
    plan: free
    region: singapore
